pipeline {
    agent {
        docker {
            image 'node:lts-buster-slim'
            args '-p 3000:3000'
        }
    }
    environment {
        CI = 'true'
    }
    stages {
        stage('Build') {
            steps {
                  sh 'npm install --cache="./cacheNode"'
            }
        }
        stage('Test') {
            steps {
                sh './jenkins/scripts/test.sh'
            }
        }
        stage('Deliver') {
            steps {
                input message: 'Do you wnat to deliver this build'
                sh 'docker save -o ./node-react-test-app node:lts-buster-slim'
                sh 'scp /home/jenkins/node-react-test-app devops@192.168.56.3:/home/devops/'
            }
        }
    }
}
